GET http://localhost:3000/characters/dashboard
content-type: application/json

    {
        "name": "Justin M",
        "race": "Orc",
        "characterClass": "Fighter",
        "armorClass": "18"
    }