POST http://localhost:3000/characters/create
content-type: application/json

    {
        "name": "Travis M",
        "race": "Elf",
        "characterClass": "Fighter",
        "armorClass": "16"
    }